---
version: "3.4"
services:
  database:
    deploy:
      mode: replicated
      replicas: "${NBR_WORKERS}"
    image: "memgraph/memgraph-platform:2.9.0-memgraph2.9.0-lab2.7.1"
    volumes:
      - ./memgraph.conf:/etc/memgraph/memgraph.conf
    environment:
      - MGCONSOLE="--username neo4j --password admin"
      - APP_CYPHER_QUERY_MAX_LEN=10000
    entrypoint: ["/usr/bin/supervisord"]
    healthcheck:
      test: ["CMD", "bash", "-c", 'mgconsole < <(echo "SHOW TRANSACTIONS;")']
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 3s
  infrahub-test:
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
