---
version: "3.4"
services:
  database:
    deploy:
      mode: replicated
      replicas: "${NBR_WORKERS}"
    image: "neo4j:5.11-enterprise"
    environment:
      - "NEO4J_AUTH=neo4j/admin"
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - "NEO4J_dbms_security_auth__minimum__password__length=4"
      - "NEO4J_server_metrics_prometheus_enabled=true"
      - "NEO4J_server_metrics_prometheus_endpoint=0.0.0.0:2004"
    volumes:
      - "./plugins:/plugins"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 2s
      timeout: 10s
      retries: 20
      start_period: 10s
  infrahub-test:
    environment:
      - "INFRAHUB_DB_TYPE=neo4j"
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
