---
version: "3.4"
services:
  infrahub-server:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "opsmill/infrahub-py${PYTHON_VER}:${IMAGE_VER}"
    command: gunicorn infrahub.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
    volumes:
      - ../:/source
    tty: true
  infrahub-git:
    build:
      context: ../
      dockerfile: development/Dockerfile
    image: "opsmill/infrahub-py${PYTHON_VER}:${IMAGE_VER}"
    command: infrahub git-agent start --debug
    depends_on:
      - infrahub-server
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
    volumes:
      - ../:/source
      - "git_data:/opt/infrahub/git"
    tty: true
volumes:
  git_data:
