---
version: "3.4"
services:

  database:
    image: "neo4j:5.1-enterprise"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_AUTH=neo4j/admin"
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
    volumes:
      - "./plugins:/plugins"

  message-queue:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
