---
version: "3.4"
services:
  infrahub-server:
    build:
      context: ../
      dockerfile: development/Dockerfile-backend
    image: "opsmill/${INFRAHUB_BUILD_NAME}-py${PYTHON_VER}:${IMAGE_VER}"
    command: gunicorn --config /source/development/gunicorn.config.py infrahub.api.main:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=DEBUG"
      - "PROMETHEUS_MULTIPROC_DIR=/prom_shared"
    volumes:
      - ../:/source
    tty: true
  infrahub-git:
    build:
      context: ../
      dockerfile: development/Dockerfile-backend
    image: "opsmill/${INFRAHUB_BUILD_NAME}-py${PYTHON_VER}:${IMAGE_VER}"
    command: infrahub git-agent start --debug
    restart: unless-stopped
    depends_on:
      - infrahub-server
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_ADDRESS=http://infrahub-server:8000"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=DEBUG"
    volumes:
      - ../:/source
      - "git_data:/opt/infrahub/git"
    tty: true
  frontend:
    build:
      context: ../
      dockerfile: development/Dockerfile-frontend
    image: "opsmill/${INFRAHUB_BUILD_NAME}-frontend:${IMAGE_VER}"
    command: >
      bash -c "npm i --omit=dev && npm run build-serve"
    depends_on:
      - infrahub-server
    volumes:
      - ../frontend/:/source
      - /source/node_modules/
    tty: true
volumes:
  git_data:
