---
version: "3.4"
services:
  message-queue:
    image: "rabbitmq:3.12-management"
    environment:
      - "RABBITMQ_DEFAULT_USER=infrahub"
      - "RABBITMQ_DEFAULT_PASS=infrahub"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3
  cache:
    image: "redis:7.2"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 3
