---
version: "3.4"
services:
  database:
    image: "neo4j:5.13-community"
    environment:
      - "NEO4J_AUTH=neo4j/admin"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - "NEO4J_dbms_security_auth__minimum__password__length=4"
    volumes:
      - "./plugins:/plugins"
      - "database_data:/data"
      - "database_logs:/logs"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 2s
      timeout: 10s
      retries: 20
      start_period: 3s

  infrahub-server:
    environment:
      - "INFRAHUB_DB_TYPE=neo4j"

  infrahub-git:
    environment:
      - "INFRAHUB_DB_TYPE=neo4j"

volumes:
  database_data:
  database_logs:
