---
# yamllint disable rule:line-length

version: "3.4"
services:
  infrahub-server:
    build:
      context: ../
      dockerfile: development/Dockerfile
      target: backend
    image: "${IMAGE_NAME}:${IMAGE_VER}"
    command: >
      gunicorn --config backend/infrahub/serve/gunicorn_config.py -w ${GUNICORN_WORKERS} --logger-class infrahub.serve.log.GunicornLogger infrahub.server:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - "${INFRAHUB_SERVER_PORT:-8000}:8000"
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=INFO"
      - "INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN=06438eb2-8019-4776-878c-0941b1f1d1ec"
      - "INFRAHUB_SECURITY_SECRET_KEY=327f747f-efac-42be-9e73-999f08f86b92"
      - "INFRAHUB_ALLOW_ANONYMOUS_ACCESS=true"
      - "INFRAHUB_DB_TYPE=${INFRAHUB_DB_TYPE}"
    volumes:
      - ../:/source
      - "storage_data:/opt/infrahub/storage"
    tty: true
    healthcheck:
      test: wget -O /dev/null http://localhost:8000/api/schema/summary || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  database:
    ports:
      - "${INFRAHUB_DB_PORT:-7687}:7687"
  vmagent:
    image: victoriametrics/vmagent:v1.97.1
    volumes:
      - vmagentdata:/vmagentdata
      - ./scale_test_vmagent.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=${METRICS_ENDPOINT:-http://127.0.0.1:8424}"
      - "--remoteWrite.label=job=scale-test"
      - "--remoteWrite.label=run_id=${GITHUB_RUN_ID}"
      - "--remoteWrite.label=run_number=${GITHUB_RUN_NUMBER}"
    ports:
      - "${VMAGENT_PORT:-8429}:8429"

volumes:
  storage_data:
  vmagentdata:
