[main]
internal_address = "http://localhost:8000"

[git]
repositories_directory = "/workspace/.infrahub/repositories"

[database]
username = "neo4j"
password = "admin"
address = "database"
port = 7687
protocol = "neo4j"
database = "infrahub"

[broker]
address = "localhost"
username = "infrahub"
password = "infrahub"

[api]
cors_allow_origins = ["*"]

[storage.settings]
directory = "/opt/infrahub/storage"