[main]
internal_address = "http://infrahub-server:8000"

[git]
repositories_directory = "/opt/infrahub/git"

[database]
username = "neo4j"
password = "admin"
address = "database"
port = 7687
protocol = "bolt"
database = "infrahub"

[broker]
address = "message-queue"
username = "infrahub"
password = "infrahub"

[api]
cors_allow_origins = ["*"]

[storage.settings]
directory = "/opt/infrahub/storage"

# [experimental_features]
# pull_request = true