[main]
internal_address = "http://infrahub-server:8000"

[git]
repositories_directory = "/opt/infrahub/git"

[database]
username = "neo4j"
password = "admin"
address = "database"
port = 7687
protocol = "bolt"

[broker]
address = "message-queue"
username = "infrahub"
password = "infrahub"

[cache]
address = "cache"

[api]
cors_allow_origins = ["*"]

[storage.settings]
directory = "/opt/infrahub/storage"

[trace]
enable = false
insecure = "True"
exporter_type = "otlp"
exporter_protocol = "grpc"
exporter_endpoint = "tempo"
exporter_port = 4317


# [experimental_features]
# pull_request = true
