[main]
internal_address = "http://infrahub-server:8000"
repositories_directory = "/opt/infrahub/git"

[database]
username = "neo4j"
password = "admin"
address = "database"
port = 7687
protocol = "neo4j"
database = "infrahub"

[broker]
address = "message-queue"
username = "infrahub"
password = "infrahub"