---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'infrahub'
    static_configs:
      - targets: ['infrahub-server:8000']
      - targets: ['infrahub-git:8000']

  - job_name: 'message-queue'
    static_configs:
      - targets: ['message-queue:15692']

  - job_name: 'database'
    static_configs:
      - targets: ['database:2004']
