---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.

# ----------------------------------
# GROUP
# ----------------------------------
- name: "group/backend"
  description: "Issue related to the backend (API Server, Git Agent)"
  color: "#b60205"

- name: "group/frontend"
  description: "Issue related to the frontend (React)"
  color: "#353755"

- name: "group/infrahubctl"
  description: "Issue related to the infrahubctl command line"
  color: "#77AB64"

- name: "group/python-sdk"
  description: "Issue related to the Python SDK"
  color: "#56E8E1"

- name: "group/sync-engine"
  description: "Issue related to the Synchronization engine"
  color: "#56E8E1"

# ----------------------------------
# TYPE
# ----------------------------------
- name: "type/feature"
  description: "New feature or request"
  color: "#a2eeef"

- name: "type/bug"
  description: "Something isn't working as expected"
  color: "#d73a4a"

- name: "type/documentation"
  description: "Improvements or additions to documentation"
  color: "#0075ca"

- name: "type/housekeeping"
  description: "Maintenance task"
  color: "#fef2c0"

- name: "type/question"
  description: "Question or discussion"
  color: "#d876e3"

- name: "type/duplicate"
  description: "This issue or pull request already exists"
  color: "#cfd3d7"

- name: "type/epic"
  description: "Large body of work composed of multiple features and/or story"
  color: "#FBD39C"


# ----------------------------------
# EFFORT
# ----------------------------------
- name: "effort/high"
  description: "This issue should be completed in more than a day"
  color: "#C80464"

- name: "effort/medium"
  description: "This issue should be completed in a less than a day"
  color: "#676A43"

- name: "effort/low"
  description: "This issue should be completed in a couple of hours"
  color: "#EAFEE4"

# ----------------------------------
# CI
# ----------------------------------

- name: "ci/skip-changelog"
  description: "Don't include this PR in the changelog"
  color: "#C30664"
