---
"group/ci":
  - .github/**

"group/backend":
  - backend/**

"group/frontend":
  - frontend/**

"group/infrahubctl":
  - ctl/**

"group/python-sdk":
  - python_sdk/**

"group/sync-engine":
  - sync/**

"type/documentation":
  - docs/**
