---
name: from-nautobot
source:
  name: nautobot
  settings:
    url: "https://demo.nautobot.com"

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: [
  "BuiltinTag",
  "BuiltinRole",
  # "BuiltinStatus",
  "CoreStandardGroup",
  "CoreOrganization",
  "TemplateLocationType",
  "BuiltinLocation",
  "InfraRack",
  "TemplateDeviceType",
  "InfraProviderNetwork",
  "TemplateCircuitType",
  "InfraCircuit",
  "InfraRouteTarget",
  "InfraVRF",
  "InfraDevice",
  "InfraVLAN",
  "InfraPrefix",
  "InfraIPAddress"
]

schema_mapping:
  # Tags
  - name: BuiltinTag
    mapping: extras.tags
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  # Roles (Device Role, Rack Role, IPAM Role, and IPAddressRoleChoices)
  - name: BuiltinRole
    mapping: extras.roles
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: label
        mapping: display

  # Status (Device Role, Rack Role, IPAM Role, and IPAddressRoleChoices)
  # - name: BuiltinStatus
  #   mapping: extras.statuses
  #   identifiers: ["name"]
  #   fields:
  #     - name: name
  #       mapping: name
  #     - name: description
  #       mapping: description
  #     - name: label
  #       mapping: display

  # Tenancy (tenants, tenant groups)
  - name: CoreStandardGroup
    mapping: tenancy.tenant-groups
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: CoreOrganization
    mapping: tenancy.tenants
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: type
        static: "Tenant"
      - name: group
        mapping: tenant_group
        reference: CoreStandardGroup

  # Locations (Location Type, Locations)
  - name: TemplateLocationType
    mapping: dcim.location-types
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: BuiltinLocation
    mapping: dcim.locations
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      # type should be removed to use location_type only, but need to change Core Schema for that
      - name: type
        mapping: location_type.name
      - name: location_type
        mapping: location_type
        reference: TemplateLocationType
      # - name: status
      #   mapping: status
      #   reference: BuiltinStatus
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Racks
  - name: InfraRack
    mapping: dcim.racks
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: location
        mapping: location
        reference: BuiltinLocation
      - name: height
        mapping: u_height
      - name: serial_number
        mapping: serial
      - name: asset_tag
        mapping: asset_tag
      - name: facility_id
        mapping: facility_id
      - name: role
        mapping: role
        reference: BuiltinRole
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Device (manufacturer, device types, devices)
  - name: CoreOrganization
    mapping: dcim.manufacturers
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: type
        static: "Manufacturer"
  - name: TemplateDeviceType
    mapping: dcim.device-types
    identifiers: ["name", "manufacturer"]
    fields:
      - name: name
        mapping: model
      - name: part_number
        mapping: part_number
      - name: full_depth
        mapping: is_full_depth
      - name: height
        mapping: u_height
      - name: tags
        mapping: tags
        reference: BuiltinTag
      - name: manufacturer
        mapping: manufacturer
        reference: CoreOrganization
  # -> The netbox constraint is `dcim_device_unique_name_site_tenant`
  # Reusing device_name + site + Organization as identifiers
  - name: InfraDevice
    identifiers: ["name", "site", "organization"]
    mapping: dcim.devices
    fields:
      - name: name
        mapping: name
      - name: serial_number
        mapping: serial
      - name: asset_tag
        mapping: asset_tag
      - name: model
        mapping: device_type
        reference: TemplateDeviceType
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: role
        mapping: role
        reference: BuiltinRole
      # - name: status
      #   mapping: status
      #   reference: BuiltinStatus
      - name: site
        mapping: location
        reference: BuiltinLocation
      - name: rack
        mapping: rack
        reference: InfraRack
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # Circuits (Provider, Provider Network, Circuits Types, Circuits)
  - name: CoreOrganization
    mapping: circuits.providers
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: type
        static: "Provider"
  - name: InfraProviderNetwork
    mapping: circuits.provider-networks
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: vendor_id
        mapping: service_id
      - name: provider
        mapping: provider.slug
      - name: description
        mapping: description
      # - name: status
      #   mapping: status
      #   reference: BuiltinStatus
      - name: tags
        mapping: tags
        reference: BuiltinTag
      - name: provider
        mapping: provider
        reference: CoreOrganization
  - name: TemplateCircuitType
    mapping: circuits.circuit-types
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
  - name: InfraCircuit
    mapping: circuits.circuits
    identifiers: ["circuit_id"]
    fields:
      - name: circuit_id
        mapping: cid
      - name: vendor_id
        mapping: cid
      - name: provider
        mapping: provider
        reference: CoreOrganization
      - name: description
        mapping: description
      # - name: status
      #   mapping: status
      #   reference: BuiltinStatus
      - name: type
        mapping: circuit_type
        reference: TemplateCircuitType
      # - name: tenant
      #   mapping: tenant
      #   reference: CoreOrganization
      - name: tags
        mapping: tags
        reference: BuiltinTag

  # BGP Plugin (Autonomous System, BGP Session, BGP Peer Group)
  - name: InfraAutonomousSystem
    mapping: plugin.bgp.autonomous-systems
    identifiers: ["name"]
    fields:
      - name: name
        mapping: asn
      - name: asn
        mapping: asn
      - name: description
        mapping: description
      - name: organization
        mapping: provider
        reference: CoreOrganization

# IPAM (VRF, VLANs Groups, VLANs, Prefixes, IPs)
  - name: InfraRouteTarget
    mapping: ipam.route-targets
    identifiers: ["name", "organization"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
  - name: InfraVRF
    mapping: ipam.vrfs
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: vrf_rd
        mapping: rd
      - name: importRT
        mapping: import_targets
        reference: InfraRouteTarget
      - name: exportRT
        mapping: export_targets
        reference: InfraRouteTarget
  - name: CoreStandardGroup
    mapping: ipam.vlan-groups
    identifiers: ["name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      # - name: location
      #   mapping: location
      #   reference: BuiltinLocation
  - name: InfraVLAN
    mapping: ipam.vlans
    identifiers: ["name", "vlan_id", "site", "organization", "vlan_group"]
    fields:
      - name: name
        mapping: name
      - name: vlan_id
        mapping: vid
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: description
        mapping: description
      - name: site
        mapping: location
        reference: BuiltinLocation
      - name: role
        mapping: role
        reference: BuiltinRole
      # - name: status
      #   mapping: status
      #   reference: BuiltinStatus
      - name: vlan_group
        mapping: vlan_group
        reference: CoreStandardGroup
  - name: InfraPrefix
    mapping: ipam.prefixes
    identifiers: ["prefix"]
    fields:
      - name: prefix
        mapping: prefix
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: role
        mapping: role
        reference: BuiltinRole
      # - name: vrf
      #   mapping: vrf
      #   reference: InfraVRF
      # - name: status
      #   mapping: status
      #   reference: BuiltinStatus
      - name: vlan
        mapping: vlan
        reference: InfraVLAN
      - name: location
        mapping: location
        reference: BuiltinLocation
  - name: InfraIPAddress
    mapping: ipam.ip-addresses
    identifiers: ["address", "prefix", "vrf"]
    fields:
      - name: address
        mapping: address
      - name: description
        mapping: description
      - name: organization
        mapping: tenant
        reference: CoreOrganization
      - name: role
        mapping: role
        reference: BuiltinRole
      # - name: status
      #   mapping: status
      #   reference: BuiltinStatus
      - name: prefix
        mapping: parent
        reference: InfraPrefix
      - name: vrf
        mapping: vrf
        reference: InfraVRF
