---
# yamllint disable rule:line-length
tasks:
  - name: Run Frontend
    before: cd frontend
    init: npm install
    command: |
      gp ports await 8000
      URL_8000=`gp url 8000`
      export REACT_APP_INFRAHUB_API_SERVER_URL=$URL_8000
      npm start
  - name: Setup Python Environment
    init: |
      pip install toml invoke
      curl -sSL https://install.python-poetry.org | python3 -
      poetry install
      cp development/docker-compose.override.yml.tmp development/docker-compose.override.yml
      invoke demo.dev-start
      gp ports await 5672
      poetry run infrahub db init
      gp sync-done python-setup
    command: invoke demo.dev-start

  - name: Run API Server
    command: |
      gp ports await 5672
      poetry run gunicorn infrahub.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  - name: Run Git Server
    command: |
      gp ports await 8000
      poetry run infrahub git-agent start --debug

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: ignore
    name: Frontend
    description: Frontend Interface
    visibility: public
  - port: 8000
    onOpen: ignore
    name: GraphQL
    description: GraphQL playground
    visibility: public

vscode:
  extensions:
    - pomdtr.excalidraw-editor
    - wholroyd.jinja
    - ms-python.vscode-pylance
    - shardulm94.trailing-spaces
    - nickmillerdev.pytest-fixtures
    - yzhang.markdown-all-in-one
    - GraphQL.vscode-graphql-syntax
