---
# yamllint disable rule:line-length
tasks:
  - name: Frontend
    before: cd frontend
    init: npm install
    command: |
      gp ports await 8000
      URL_8000=`gp url 8000`
      export REACT_APP_INFRAHUB_API_SERVER_URL=$URL_8000
      npm start
  - name: CLI
    init: |
      pyenv install 3.10
      pyenv local 3.10
      pip install toml invoke
      curl -sSL https://install.python-poetry.org | python3 -
      poetry config virtualenvs.create false
      source ~/.bashrc
      poetry install
      cp development/docker-compose.override.yml.tmp development/docker-compose.override.yml
      invoke demo.dev-start
      gp ports await 5672
      sleep 45
      infrahub db init
    command: |
      invoke demo.dev-start
      gp sync-done python-setup
  - name: Backend API
    command: |
      gp ports await 5672
      gp sync-await python-setup
      gunicorn infrahub.api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  - name: Git Agent
    command: |
      gp ports await 8000
      mkdir -p /workspace/.infrahub/repositories
      export INFRAHUB_CONFIG=/workspace/infrahub/development/gitpod.infrahub.toml
      infrahub git-agent start --debug

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: ignore
    name: Frontend
    description: Frontend Interface
    visibility: public
  - port: 8000
    onOpen: ignore
    name: GraphQL
    description: GraphQL playground
    visibility: public
  - port: 7474
    onOpen: ignore
    name: neo4j-ui
    description: Graphical interface for Neo4j
    visibility: private
  - port: 7687
    onOpen: ignore
    name: neo4j-api
    description: API for Neo4j
    visibility: private
  - port: 15672
    onOpen: ignore
    name: rabbitmq-1
    visibility: private
  - port: 5672
    onOpen: ignore
    name: rabbitmq-2
    visibility: private
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

vscode:
  extensions:
    - pomdtr.excalidraw-editor
    - wholroyd.jinja
    - ms-python.vscode-pylance
    - shardulm94.trailing-spaces
    - nickmillerdev.pytest-fixtures
    - yzhang.markdown-all-in-one
    - GraphQL.vscode-graphql-syntax
