---
# yamllint disable rule:line-length
tasks:
  - name: CLI
    before: |
      printf 'export PATH="%s:$PATH"\n' "/home/gitpod/.local/bin" >> $HOME/.bashrc
      URL_8000=`gp url 8000`
      export VITE_INFRAHUB_API_SERVER_URL=$URL_8000
    init: |
      cp development/docker-compose.gitpod-override.yml development/docker-compose.override.yml
      pyenv install 3.10 --skip-existing
      pyenv local 3.10
      pip install toml invoke==2.0.0
      curl -sSL https://install.python-poetry.org | python3 -
      source $HOME/.bashrc
      poetry config virtualenvs.create false
      poetry install
      poetry run invoke demo.build demo.init demo.start
    command: |
      source $HOME/.bashrc
      poetry run invoke demo.build demo.start demo.load-infra-schema demo.load-infra-data

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: ignore
    name: Frontend
    description: Frontend Interface
    visibility: public
  - port: 8000
    onOpen: ignore
    name: GraphQL
    description: GraphQL playground
    visibility: public
  - port: 7474
    onOpen: ignore
    name: neo4j-ui
    description: Graphical interface for Neo4j
    visibility: private
  - port: 7687
    onOpen: ignore
    name: neo4j-api
    description: API for Neo4j
    visibility: private
  - port: 15672
    onOpen: ignore
    name: rabbitmq-1
    visibility: private
  - port: 5672
    onOpen: ignore
    name: rabbitmq-2
    visibility: private
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

workspaceLocation: "."
additionalRepositories:
  - url: https://github.com/opsmill/infrahub-demo-edge-develop
    # checkoutLocation is relative to /workspaces
    checkoutLocation: infrahub-demo-edge

vscode:
  extensions:
    - pomdtr.excalidraw-editor
    - wholroyd.jinja
    - ms-python.vscode-pylance
    - shardulm94.trailing-spaces
    - nickmillerdev.pytest-fixtures
    - yzhang.markdown-all-in-one
    - GraphQL.vscode-graphql-syntax
