[tool.poetry]
name = "infrahub"
version = "0.1.0"
description = ""
authors = ["Damien Garros <dgarros@gmail.com>"]

packages = [
    { include = "infrahub" },
    { include = "infrahub_client" },
]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "~0.81"
neo4j = "~5.3"
pendulum = "~2.1"
uvicorn = {version = "~0.18", extras = ["standard"]}
graphene = "~3.2"
rich = "^12.0.0"
starlette-exporter = "^0.12.0"
typer = "^0.6"
GitPython = "^3.1.27"
Jinja2 = "^3.1.2"
httpx = "^0.23.0"
toml = "^0.10.2"
jsonlines = "^3.0.0"
gunicorn = "^20.1.0"
deepdiff = "^5.8.1"
aio-pika = "^8.2.0"
ujson = "^5.7.0"

[tool.poetry.dev-dependencies]
black = "*"
pytest = "*"
yamllint = "*"
pylint = "*"
flake8 = "^5.0"
mypy = "*"
ipython = "*"
pytest-asyncio = "*"
requests = "*"
pre-commit = "^2.20.0"
isort = "*"
autoflake = "*"
pytest-clarity = "^1.0.1"
locust = "^2.13.1"
pytest-httpx = "^0.21.2"
types-toml = "^0.10.8"

[tool.poetry.scripts]
infrahub = "infrahub.cli:app"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
        /(
          \.git
        | \.tox
        | \.venv
        | env/
        | _build
        | build
        | dist
        | examples
        )/
    '''

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true

[tool.pylint.general]
extension-pkg-whitelist = [
    "pydantic"
]

[tool.pylint.format]
disable = "logging-fstring-interpolation"

[tool.pylint.basic]
# No docstrings required for private methods (Pylint default), or for test_ functions.
no-docstring-rgx="^(_|test_)"

[tool.pylint.messages_control]
# Line length is enforced by Black, so pylint doesn't need to check it.
# Pylint and Black disagree about how to format multi-line arrays; Black wins.
disable = """,
    line-too-long,
    missing-module-docstring,
    missing-function-docstring,
    missing-class-docstring,
    consider-using-from-import,
    invalid-name,
    too-many-arguments,
    keyword-arg-before-vararg,
    too-few-public-methods,
    """

[tool.pylint.miscellaneous]
notes = """,
    FIXME,
    XXX,
    """

[tool.pylint.similarities]
min-similarity-lines = 20

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
    "tests"
]
filterwarnings = [
    "ignore:Module already imported so cannot be rewritten",
]

[tool.mypy]
pretty = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
