{{- if .Values.infrahubDemoData.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-infrahub-demo-data-job
  labels:
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.infrahubDemoData.backoffLimit }}
  template:
    spec:
      containers:
        - command:
            - sh
            - -c
            - "infrahubctl schema load models/base --wait 30 || infrahubctl schema load models/infrastructure_base.yml && infrahubctl run models/infrastructure_edge.py"
          env:
            - name: INFRAHUB_ADDRESS
              value: http://{{ include "infrahub-helm.fullname" . }}-infrahub-server.{{ .Release.Namespace }}.svc.{{ .Values.global.kubernetesClusterDomain }}:8000
            - name: INFRAHUB_INTERNAL_ADDRESS
              value: "http://{{ include "infrahub-helm.fullname" . }}-infrahub-server.{{ .Release.Namespace }}.svc.{{ .Values.global.kubernetesClusterDomain }}:8000"
            - name: INFRAHUB_DATABASE_ADDRESS
              value: "{{ include "infrahub-helm.fullname" . }}-database.{{ .Release.Namespace }}.svc.{{ .Values.global.kubernetesClusterDomain }}"
            - name: INFRAHUB_DATABASE_PORT
              value: "{{ .Values.neo4j.services.neo4j.ports.bolt.port }}"
            - name: INFRAHUB_BROKER_ADDRESS
              value: "{{ include "infrahub-helm.fullname" . }}-message-queue.{{ .Release.Namespace }}.svc.{{ .Values.global.kubernetesClusterDomain }}"
            - name: INFRAHUB_BROKER_USERNAME
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: INFRAHUB_BROKER_PASSWORD
              value: {{ .Values.rabbitmq.auth.password | quote }}
            - name: INFRAHUB_CACHE_ADDRESS
              value: "{{ include "infrahub-helm.fullname" . }}-cache-master.{{ .Release.Namespace }}.svc.{{ .Values.global.kubernetesClusterDomain }}"
            - name: INFRAHUB_CACHE_PORT
              value: "{{ .Values.redis.master.service.ports.redis }}"
          {{- with .Values.infrahubDemoData.env }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.infrahubServer.infrahubServer.envFromExistingSecret }}
          envFrom:
            - secretRef:
                name: {{ . }}
          {{- end }}
          image: {{ default .Values.global.imageRegistry .Values.infrahubDemoData.imageRegistry }}/{{ .Values.global.infrahubRepository }}:{{ .Values.global.infrahubTag | default .Chart.AppVersion }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.infrahubDemoData.imagePullPolicy }}
          name: infrahub-demo-data-job
          resources: {}
      restartPolicy: Never
{{- end }}
