---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-infrahub-git
  labels:
    service: infrahub-git
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.infrahubGit.replicas }}
  selector:
    matchLabels:
      service: infrahub-git
    {{- include "infrahub-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: infrahub-git
      {{- include "infrahub-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args: {{- toYaml .Values.infrahubGit.infrahubGit.args | nindent 12 }}
          env:
            - name: INFRAHUB_ADDRESS
              value: {{ quote .Values.infrahubGit.infrahubGit.env.infrahubAddress }}
            - name: INFRAHUB_CACHE_PORT
              value: {{ quote .Values.infrahubServer.infrahubServer.env.infrahubCachePort }}
            - name: INFRAHUB_CONFIG
              value: {{ quote .Values.infrahubGit.infrahubGit.env.infrahubConfig }}
            - name: INFRAHUB_DB_TYPE
              value: {{ quote .Values.infrahubGit.infrahubGit.env.infrahubDbType }}
            - name: INFRAHUB_LOG_LEVEL
              value: {{ quote .Values.infrahubGit.infrahubGit.env.infrahubLogLevel }}
            - name: INFRAHUB_PRODUCTION
              value: {{ quote .Values.infrahubGit.infrahubGit.env.infrahubProduction }}
            - name: INFRAHUB_SDK_API_TOKEN
              value: {{ quote .Values.infrahubGit.infrahubGit.env.infrahubSdkApiToken }}
            - name: INFRAHUB_SDK_TIMEOUT
              value: {{ quote .Values.infrahubGit.infrahubGit.env.infrahubSdkTimeout }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          image: {{ .Values.infrahubRepository }}:{{ .Values.infrahubTag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.infrahubGit.infrahubGit.imagePullPolicy }}
          name: infrahub-git
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /opt/infrahub/git
              name: git-data
            - mountPath: /remote
              name: git-remote-data
            - name: infrahub-config-volume
              mountPath: /config
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /tmp/infrahub-helm
          name: git-data
        - hostPath:
            path: /tmp/infrahub-helm
          name: git-remote-data
        - name: infrahub-config-volume
          configMap:
            name: {{ .Chart.Name }}-{{ .Chart.AppVersion }}-configmap

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-git-data
  labels:
    service: git-data
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.gitData.storageRequest | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-git-remote-data
  labels:
    service: git-remote-data
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.gitRemoteData.storageRequest | quote }}
