---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-viewer
  namespace: {{ quote .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-job-viewer
  labels:
  {{- include "infrahub-helm.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-job-viewer-binding
  labels:
  {{- include "infrahub-helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "infrahub-helm.fullname" . }}-job-viewer
subjects:
  - kind: ServiceAccount
    name: job-viewer
    namespace: {{ quote .Release.Namespace }}
