---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-message-queue
  labels:
    service: message-queue
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.messageQueue.replicas }}
  selector:
    matchLabels:
      service: message-queue
    {{- include "infrahub-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        service: message-queue
      {{- include "infrahub-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ quote .Values.messageQueue.messageQueue.env.rabbitmqDefaultPass }}
            - name: RABBITMQ_DEFAULT_USER
              value: {{ quote .Values.messageQueue.messageQueue.env.rabbitmqDefaultUser }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          image: {{ .Values.messageQueue.messageQueue.image.repository }}:{{ .Values.messageQueue.messageQueue.image.tag }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - rabbitmq-diagnostics -q ping
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 30
          name: message-queue
          ports:
          {{- range .Values.messageQueue.ports }}
            - containerPort: {{ .targetPort }}
              hostPort: {{ .port }}
              protocol: TCP
              name: {{ quote .name }}
          {{- end }}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-message-queue
  labels:
    service: message-queue
  {{- include "infrahub-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.messageQueue.type }}
  selector:
    service: message-queue
  {{- include "infrahub-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.messageQueue.ports | toYaml | nindent 4 }}
