---
apiVersion: 1

datasources:
  - name: Prometheus (Local)
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    editable: true

  - name: Loki (Local)
    type: loki
    url: http://loki:3100
