---
apiVersion: 1

datasources:
  - name: Prometheus (Local)
    type: prometheus
    uid: localprometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    editable: true

  - name: Loki (Local)
    type: loki
    uid: localloki
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: 'TraceID=0x(\w+)'
          url: '$${__value.raw}'
          urlDisplayLabel: "View Trace via TraceID (in Tempo)"
          datasourceUid: 'localtempo'
        - name: RequestID
          matcherRegex: 'RequestID=(\w+)'
          url: '{name=~".*$${__value.raw}.*"}'
          urlDisplayLabel: "View Trace via RequestID (in Tempo)"
          datasourceUid: 'localtempo'

  - name: Tempo (Local)
    type: tempo
    uid: localtempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'localloki'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'localprometheus'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'localloki'
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
