---
name: from-netbox
source:
  name: netbox
  settings:
    url: "https://demo.netbox.dev"
    token: "95c5b9131943fe3b59f483e1992a3b8d7ab266e9"

destination:
  name: infrahub
  settings:
    url: "http://localhost:8000"

order: ["tag", "location", "role", "rack"]

schema_mapping:
  - name: tag
    mapping: extras.tags
    fields:
      - name: name
        mapping: name
        identifier: true
      - name: description
        mapping: description

  - name: location
    mapping: dcim.sites
    fields:
      - name: name
        mapping: slug
      - name: description
        mapping: description
      - name: type
        static: "SITE"

  - name: rack
    mapping: dcim.racks
    identifiers: ["location", "name"]
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
      - name: location
        mapping: site.slug
      - name: height
        mapping: u_height
      # - name: tags
      #   reference:
      #     key: tags


  - name: role
    mapping: dcim.device_roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  - name: role
    mapping: dcim.rack_roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description

  - name: role
    mapping: ipam.roles
    fields:
      - name: name
        mapping: name
      - name: description
        mapping: description
