cache:
  cache:
    image:
      repository: redis
      tag: "7.2"
  ports:
  - name: "client"
    port: 6379
    targetPort: 6379
  - name: "gossip"
    port: 16379
    targetPort: 16379
  replicas: 1
  type: ClusterIP
database:
  database:
    env:
      neo4JAcceptLicenseAgreement: "yes"
      neo4JAuth: neo4j/admin
      neo4JDbmsSecurityAuthMinimumPasswordLength: "4"
      neo4JDbmsSecurityProceduresUnrestricted: apoc.*
      neo4JServerMetricsPrometheusEnabled: "true"
      neo4JServerMetricsPrometheusEndpoint: 0.0.0.0:2004
    image:
      repository: neo4j
      tag: 5.11-enterprise
  ports:
  - name: "metrics"
    port: 2004
    targetPort: 2004
  - name: "interface"
    port: 7474
    targetPort: 7474
  - name: "bolt"
    port: 7687
    targetPort: 7687
  replicas: 1
  type: ClusterIP
infrahubGit:
  infrahubGit:
    args:
    - infrahub
    - git-agent
    - start
    - --debug
    env:
      infrahubAddress: http://infrahub-server:8000
      infrahubCachePort: 6379
      infrahubConfig: /config/infrahub.toml
      infrahubDbType: neo4j
      infrahubLogLevel: DEBUG
      infrahubProduction: "false"
      infrahubSdkApiToken: 06438eb2-8019-4776-878c-0941b1f1d1ec
      infrahubSdkTimeout: "20"
    image:
      repository: 9r2s1098.c1.gra9.container-registry.ovh.net/opsmill/infrahub
    imagePullPolicy: Always
  replicas: 2
  waitForInfrahubServer:
    image:
      repository: busybox
      tag: latest
infrahubServer:
  infrahubServer:
    args:
    - gunicorn
    - --config
    - /source/backend/infrahub/serve/gunicorn_config.py
    - --logger-class
    - infrahub.serve.log.GunicornLogger
    - infrahub.server:app
    env:
      infrahubAllowAnonymousAccess: "true"
      infrahubCachePort: 6379
      infrahubConfig: /config/infrahub.toml
      infrahubDbType: neo4j
      infrahubFrontendDirectory: /opt/infrahub/frontend
      infrahubLogLevel: INFO
      infrahubProduction: "false"
      infrahubSecurityInitialAdminToken: 06438eb2-8019-4776-878c-0941b1f1d1ec
      infrahubSecuritySecretKey: 327f747f-efac-42be-9e73-999f08f86b92
      prometheusMultiprocDir: /prom_shared
    image:
      repository: 9r2s1098.c1.gra9.container-registry.ovh.net/opsmill/infrahub
    imagePullPolicy: Always
  ports:
  - name: "infrahub-gui"
    port: 8000
    targetPort: 8000
  replicas: 1
  type: ClusterIP
  waitForCache:
    image:
      repository: busybox
      tag: latest
  waitForDatabase:
    image:
      repository: busybox
      tag: latest
  waitForMessageQueue:
    image:
      repository: busybox
      tag: latest
infrahubServerDbInitJob:
  backoffLimit: 0
  infrahubServerDbInitJob:
    env:
      infrahubCachePort: 6379
      infrahubConfig: /config/infrahub.toml
    image:
      repository: 9r2s1098.c1.gra9.container-registry.ovh.net/opsmill/infrahub
  waitForDatabase:
    image:
      repository: busybox
      tag: latest
kubernetesClusterDomain: cluster.local
messageQueue:
  messageQueue:
    env:
      rabbitmqDefaultPass: infrahub
      rabbitmqDefaultUser: infrahub
    image:
      repository: rabbitmq
      tag: 3.12-management
  ports:
  - name: "4369"
    port: 4369
    targetPort: 4369
  - name: "5671"
    port: 5671
    targetPort: 5671
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15671"
    port: 15671
    targetPort: 15671
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "15691"
    port: 15691
    targetPort: 15691
  - name: "15692"
    port: 15692
    targetPort: 15692
  - name: "2567"
    port: 2567
    targetPort: 2567
  replicas: 1
  type: ClusterIP
pvc:
  databaseClaim0:
    storageRequest: 100Mi
  databaseData:
    storageRequest: 100Mi
  databaseLogs:
    storageRequest: 100Mi
  gitData:
    storageRequest: 100Mi
  gitRemoteData:
    storageRequest: 100Mi
  infrahubGitClaim2:
    storageRequest: 100Mi
  infrahubServerClaim1:
    storageRequest: 100Mi
  infrahubServerStorageData:
    storageRequest: 100Mi
