---
# yamllint disable rule:truthy
name: "Backend"
on:
  pull_request:
    paths:
      - backend/
      - development/
      - pyproject.toml
      - poetry.lock
      - tasks.py

env:
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: admin
  NEO4J_ADDRESS: localhost
  NEO4J_PORT: 7687
  NEO4J_PROTOCOL: neo4j

jobs:
  python-tests:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup Python environment"
        run: "pip install poetry==1.3.2 toml invoke"
      - name: "Setup Git"
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "infrahub@example.com"
          git config --global user.name "Infrahub"
      - name: "Setup Docker-Compose"
        run: cp development/docker-compose.override.yml.tmp development/docker-compose.override.yml
      - name: "Start database"
        run: "invoke dev-start"
      - name: "Install project"
        run: "poetry install --only=dev,server"
      # - name: "Pylint Tests"
      #   run: "poetry run invoke pylint"
      - name: "Unit Tests"
        run: "poetry run pytest -v backend/tests/unit"
      - name: "Integration Tests : User Workflows"
        run: "poetry run pytest -v backend/tests/integration/user_workflows/"
