---
# yamllint disable rule:truthy
name: Coveralls report
on:
  push:
    branches:
      - develop
      - stable
  pull_request:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      # NOTE: The ref value should be different when triggered by pull_request event.
      #       See: https://github.com/lewagon/wait-on-check-action/issues/25.
      - name: Wait on tests (PR)
        uses: lewagon/wait-on-check-action@e106e5c43e8ca1edea6383a39a01c5ca495fd812
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: report
          allowed-conclusions: success,skipped,cancelled,failure

      - name: Wait on tests (push)
        if: github.event_name != 'pull_request'
        uses: lewagon/wait-on-check-action@e106e5c43e8ca1edea6383a39a01c5ca495fd812
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: report
          allowed-conclusions: success,skipped,cancelled,failure

#       - uses: coverallsapp/github-action@v2
#         env:
#           COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
#         with:
#           carryforward: "backend-unit,backend-integration,infrahubctl-unit,python-sdk-unit,python-sdk-integration"
#           parallel-finished: true
