---
# yamllint disable rule:truthy
name: "Frontend"
on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  push:
    branches:
      - develop
      - stable

env:
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: admin
  NEO4J_ADDRESS: localhost
  NEO4J_PORT: 7687
  NEO4J_PROTOCOL: neo4j

jobs:
  frontend-tests:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Setup Python environment"
        run: "pip install poetry==1.3.2 toml invoke==2.0.0"
      - name: "Install frontend"
        working-directory: ./frontend
        run: npm install
      - name: "Run integration tests"
        working-directory: ./frontend
        run: "npm run cypress:run"
      - name: "Run unit tests"
        working-directory: ./frontend
        run: "npm run test:coverage"
      - name: "Coveralls : Unit Tests"
        uses: coverallsapp/github-action@v2.0.0
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
        with:
          flag-name: frontend-unit
          parallel: true
          file: frontend/coverage/lcov.info
          # - name: "Start backend"
          #   run: |
          #     cp development/docker-compose.override.yml.tmp development/docker-compose.override.yml
          #     invoke demo.dev-start demo.build demo.init demo.start
          # - name: "Run integration tests"
          #   working-directory: ./frontend
          #   run: "npm run cypress:run"
