---
# yamllint disable rule:truthy
name: "infrahubctl"
on:
  pull_request:
    paths:
      - "infrahub_ctl/**"
      - pyproject.toml
      - poetry.lock
      - tasks.py

jobs:
  python-tests:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup Python environment"
        run: "pip install poetry==1.3.2 toml invoke"
      - name: "Setup Git"
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "infrahub@example.com"
          git config --global user.name "Infrahub"
      - name: "Install project"
        run: "poetry install --only=main,dev,cli,sdk"
      - name: "Flake8 Tests"
        run: "poetry run invoke ctl.flake8"
      - name: "Pylint Tests"
        run: "poetry run invoke ctl.pylint"
      - name: "Mypy Tests"
        run: "poetry run invoke ctl.mypy"
      - name: "Unit Tests"
        run: "poetry run pytest -v --cov=infrahub_ctl --cov-report term-missing infrahub_ctl/tests/unit"
