---
# yamllint disable rule:truthy
name: "Linting"
on:
  pull_request:
  push:
    branches:
      - develop
      - stable

jobs:
  yaml-lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Setup environment"
        run: "pip install yamllint==1.29.0"
      - name: "Linting: yamllint"
        run: "yamllint ."
  python-lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Setup environment"
        run: "pip install black==23.1.0"
      - name: "Linting: BLACK"
        run: "black --check ."
  # javascript-lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Check out repository code"
  #       uses: "actions/checkout@v3"
  #     - name: Install NodeJS
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #     - name: Install frontend dependencies
  #       working-directory: ./frontend
  #       run: npm install
  #     - name: Run ESLint
  #       working-directory: ./frontend
  #       run: npm run eslint
