---
# yamllint disable rule:truthy
name: New Release

on:
  push:
    tags:
      - '*'

jobs:
  meta_data:
    runs-on: ubuntu-22.04
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Set docker image meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.HARBOR_HOST }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

  publish-docker-image:
    uses: ./.github/workflows/ci-docker-image.yml
    secrets: inherit
    needs: meta_data
    with:
      publish: true
      version: ${{ github.ref_name }}
      ref: ${{ github.sha }}
      tags: ${{ needs.meta_data.outputs.tags }}
      labels: ${{ needs.meta_data.outputs.labels }}
