---
# yamllint disable rule:truthy
name: "Testing"
on:
  - "push"
  - "pull_request"

env:
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: admin
  NEO4J_ADDRESS: localhost
  NEO4J_PORT: 7687
  NEO4J_PROTOCOL: neo4j

jobs:
  python-tests:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup Python environment"
        run: "pip install poetry==1.1.15 toml invoke"
      - name: "Setup Git"
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "infrahub@example.com"
          git config --global user.name "Infrahub"
      - name: "Setup Docker-Compose"
        run: cp development/docker-compose.override.yml.tmp development/docker-compose.override.yml
      - name: "Start database"
        run: "invoke dev-start"
      - name: "Install project"
        run: "poetry install"
      - name: "Pylint Tests"
        run: "invoke pylint"
      - name: "Unit Tests"
        run: "poetry run infrahub test unit"
      - name: "Integration Tests : Client"
        run: "poetry run infrahub test integration tests/integration/client/"
      - name: "Integration Tests : User Workflows"
        run: "poetry run infrahub test integration tests/integration/user_workflows/"
      - name: "Client Tests"
        run: "poetry run infrahub test client"
      - name: "CTL Tests"
        run: "poetry run infrahub test ctl"
